#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx lint-staged
echo 'Styling, testing and building your project before commiting'

# npm run test-all

npm run check-format || (
       echo '🤢🤮Your styling looks disgusting🤢🤮 Prettier check failed !! Run `npm run format`, add changes and try commit again.'
       false;
)
npm run check-lint || (
       echo '😤🏀Get that weak shit out of here😤🏀 ESLint Check Failed !! Make the required changes listed above, add changes and try to commit again.'
       false;
)
npm run check-types || (
       echo '🤡😂Failed Check Types😂🤡 Are you seriously trying to write that ? Make the changes required above.'
       false;
)

echo '🤔🤔...Alright ^_^... Code looks good to me... Trying to build now.🤔🤔'

npm run build ||
(
       echo '❌👷🔨❌ Opps!! Build Failed ❌👷🔨❌ Next build failed: View the errors above to see why.'
       false;
)

echo  '✅✅✅✅ You win this time... I am comming this now...  Building successfully !! ✅✅✅✅'undefined
