#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo 'Styling, testing and building your project before commiting'

npm run check-format || (
       echo '🤢🤮🤢 Prettier check failed !! 🤢🤮🤢  Run `npx prettier . --write`, add changes and try commit again.'
       false;
)
npm run check-lint || (
       echo '😤🏀❌ ESLint Check Failed !! 😤🏀❌  Make the required changes listed above, add changes and try to commit again.'
       false;
)
npm run check-types || (
       echo '🤡😂 Failed Check Types !! 😂🤡 Are you seriously trying to write that ? Make the changes required above.'
       false;
)

echo '🤔🤔 Alright ! Code looks good. 🤔🤔'



echo  '✅ Pass all tests successfully! ✅'